services:
  shacl-validator:
    image: isaitb/shacl-validator
    restart: unless-stopped
    ports:
    - 8088:8080
    environment:
    - validator.resourceRoot=/validator/resources
    - validator.domain=tree,ldes
    - validator.restrictResourcesToDomain=false
    volumes:
    - ./resources:/validator/resources/
    healthcheck:
      start_period: 5s
      test: wget -qO- http://shacl-validator:8080/shacl/ldes/upload
      interval: 3s
      timeout: 1s
      retries: 10
